name: Verify Gem Build

on:
  pull_request:
    paths:
      - 'dev/shopify_product_taxonomy.gemspec'
      - 'dev/lib/**/*'
      - '.github/workflows/build_gem.yml'

jobs:
  build:
    name: Verify Gem Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          working-directory: dev
          bundler-cache: true

      - name: Build gem
        working-directory: dev
        run: gem build shopify_product_taxonomy.gemspec
